steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/scenic-patrol-389508/demo-app'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: '600s' # Optional: Increase the timeout if needed
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/scenic-patrol-389508/demo-app'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'demo-app'
      - '--image'
      - 'gcr.io/scenic-patrol-389508/demo-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south2'
