steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/scenic-patrol-389508/demoServiceImg', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/scenic-patrol-389508/demoServiceImg']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'demo-service', '--image', 'gcr.io/scenic-patrol-389508/demoServiceImg', '--platform', 'managed', '--region', 'asia-south2']
